#ifndef _SYS_ERRNO_H
#define _SYS_ERRNO_H 1


#define E2BIG 1
#define EACCES 2
#define EADDRINUSE 3
#define EADDRNOTAVAIL 5
#define EAFNOSUPPORT 6
#define EAGAIN 7
#define EALREADY 8
#define EBADF 9
#define EBADMSG 10
#define EBUSY 11
#define ECANCELED 12
#define ECHILD 13
#define ECONNABORTED 14
#define ECONNREFUSED 15
#define ECONNRESET 16
#define EDEADLK 17
#define EDESTADDRREQ 18
#define EDOM 19
#define EDQUOT 20
#define EEXIST 21
#define EFAULT 22
#define EFBIG 23
#define EHOSTUNREACH 24
#define EIDRM 25
#define EILSEQ 26
#define EINPROGRESS 27
#define EINTR 28
#define EINVAL 29
#define EIO 30
#define EISCONN 31
#define EISDIR 32
#define ELOOP 33
#define EMFILE 34
#define EMLINK 35
#define EMSGSIZE 36
#define EMULTIHOP 37
#define ENAMETOOLONG 38
#define ENETDOWN 39
#define ENETRESET 40
#define ENETUNREACH 41
#define ENFILE 42
#define ENOBUFS 43
#define ENODATA 44
#define ENODEV 45
#define ENOENT 46
#define ENOEXEC 47
#define ENOLCK 48
#define ENOLINK 49
#define ENOMEM 50
#define ENOMSG 51
#define ENOPROTOOPT 52
#define ENOSPC 53
#define ENOSR 54
#define ENOSTR 55
#define ENOSYS 56
#define ENOTCONN 57
#define ENOTDIR 58
#define ENOTEMPTY 59
#define ENOTRECOVERABLE 60
#define ENOTSOCK 61
#define ENOTSUP 62
#define ENOTTY 63
#define ENOXIO 64
#define EOPNOTSUPP 65
#define EOVERFLOW 66
#define EOWNERDEAD 67
#define EPERM 68
#define EPIPE 69
#define EPROTO 70
#define EPROTONOSUPPORT 71
#define EPROTOTYPE 72
#define ERANGE 73
#define EROFS 74
#define ESPIPE 75
#define ESRCH 76
#define ESTALE 77
#define ETIME 78
#define ETIMEDOUT 79
#define ETXTBSY 80
#define EWOULDBLOCK 81
#define EXDEV 82

#endif