
all: 
	$(MAKE) -C test && \
	$(MAKE) -C clock && \
	$(MAKE) -C background



clean:
	$(MAKE) -C test clean && \
	$(MAKE) -C clock clean && \
	$(MAKE) -C background clean



.PHONY: clean



