
all: 
	$(MAKE) -C test && \
	$(MAKE) -C clock && \
	$(MAKE) -C background && \
	$(MAKE) -C battery



clean:
	$(MAKE) -C test clean && \
	$(MAKE) -C clock clean && \
	$(MAKE) -C background clean && \
	$(MAKE) -C battery clean



.PHONY: clean



